chore(pubchem): in case of error/not found show "not found" text
zakodium/c6h6-react pull request #11
Opened 2021-03-27 14:18 UTC by kjappelbaum

- in case of error show a "not found" text instead of nothing
- for the computed properties use the labels and rename reference column
- bumping dependencies

2021-03-27 17:09 UTC, kjappelbaum commented
@lpatiny could you maybe give it a look?

2021-03-27 17:17 UTC, targos commented on src/components/chemistry/pubchem/computed/Computed.tsx
> +      <CompactTd style={{ whiteSpace: 'normal' }}>{row.label}</CompactTd>
Tailwind has a `whitespace-normal` class: https://tailwindcss.com/docs/whitespace#class-reference

2021-03-29 06:13 UTC, targos requested changes

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/computed/Computed.tsx
> +      tableStyle={{ width: '50%' }}
can't we use `w-1/2` in the class ?

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/computed/Computed.tsx
> +    <tr key="computedPropertiesHeader">
```suggestion
    <tr>
```

In React, keys must be used when arrays of elements are returned or in rare cases to force React to completely re-render a component subtree. This key doesn't really have any effect.

https://reactjs.org/docs/lists-and-keys.html#keys

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/computed/Computed.tsx
> +      <Th className="w-1/4">Label </Th>
```suggestion
      <Th className="w-1/4">Label</Th>
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/full/PStatementsTableFull.tsx
> +  if (!pStatements || pStatements.length < 1) {
```suggestion
  if (!pStatements || pStatements.length 
  === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/full/HStatementsTableFull.tsx
> +  if (!hStatements || hStatements.length < 1) {
```suggestion
  if (!hStatements || hStatements.length === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/full/PictogramsTableFull.tsx
> +  if (!pictograms || pictograms.length < 1) {
```suggestion
  if (!pictograms || pictograms.length === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/summary/HStatementsTable.tsx
> +  if (!props.hStatements || props.hStatements.length < 1) {
```suggestion
  if (!props.hStatements || props.hStatements.length === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/summary/PStatementsTable.tsx
> +  if (!props.pStatements || props.pStatements.length < 1) {
```suggestion
  if (!props.pStatements || props.pStatements.length === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/summary/PictogramsTable.tsx
> +    <tr key="pictogramTableHeader">
```suggestion
    <tr>
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/ghs/summary/PictogramsTable.tsx
> +  if (!props.pictograms || props.pictograms.length < 1) {
```suggestion
  if (!props.pictograms || props.pictograms.length === 0) {
```

2021-03-29 06:13 UTC, targos commented on src/components/chemistry/pubchem/index.tsx
> +import { ErrorPage } from '@/components/tailwind-ui';
Please reorder this import according to the ESLint warning

2021-03-29 06:13 UTC, targos commented on src/components/tailwind-ui/lists/Table.tsx
> +  wrap?: boolean;
Files in `tailwind-ui` cannot be modified here as they come from another repository.
What's the problem that you are trying to fix with this change?

2021-03-29 15:04 UTC, kjappelbaum commented on src/components/tailwind-ui/lists/Table.tsx
> +  wrap?: boolean;
Sorry, i didn't realize this. It was because i wanted to use the class as suggested in https://github.com/zakodium/c6h6-react/pull/11#discussion_r602757019.

2021-03-29 15:08 UTC, targos commented on src/components/tailwind-ui/lists/Table.tsx
> +  wrap?: boolean;
Ok, sorry, I didn't realize you needed to override an existing class :D

2021-03-29 15:11 UTC, merged